services:
  web-main:
    image: nginx:1.28
    container_name: web-main
    ports:
      - 80:80
    volumes:
      - ./config:/etc/nginx/conf.d:ro
      - ./main:/usr/share/nginx/html:ro
    depends_on:
      - web-sub1
      - web-sub2
      - backend
  web-sub1:
    image: nginx:1.28
    container_name: web-sub1
    volumes:
      - ./frontend/dist:/usr/share/nginx/html:ro
      - ./config:/etc/nginx/conf.d:ro
  backend:
    image: uv:1
    container_name: backend
    volumes:
      - ./backend:/workspace
    command: ["uv", "run", "fastapi", "run", "--proxy-headers", "--forwarded-allow-ips", "'*'"]
  spark-master:
    image: apache/spark:4.1.1-java21-python3
    container_name: spark-master
    user: root
    environment:
      - SPARK_MASTER_HOST=spark-master
      - SPARK_MASTER_PORT=7077
      - SPARK_MASTER_WEBUI_PORT=8080
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - "8080:8080"
      
    networks:
      - spark-network
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master

  spark-worker-1:
    image: apache/spark:4.1.1-java21-python3
    container_name: spark-worker-1
    user: root
    environment:
      - SPARK_WORKER_MEMORY=2G
      - SPARK_WORKER_CORES=2
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
    volumes:
      - spark-work-1:/opt/spark/work
    depends_on:
      - spark-master
    networks:
      - spark-network
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077

  spark-worker-2:
    image: apache/spark:4.1.1-java21-python3
    container_name: spark-worker-2
    user: root
    environment:
      - SPARK_WORKER_MEMORY=2G
      - SPARK_WORKER_CORES=2
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
    volumes:
      - spark-work-2:/opt/spark/work
    depends_on:
      - spark-master
    networks:
      - spark-network
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077

networks:
  spark-network:
    driver: bridge

volumes:
  spark-work-1:
  spark-work-2:
  