services:
  web-main:
    image: nginx:1.28
    container_name: web-main
    ports:
      - 80:80
    volumes:
      - ./config:/etc/nginx/conf.d:ro
      - ./main:/usr/share/nginx/html:ro
    depends_on:
      - web-sub1
      - web-sub2
      - backend
  web-sub1:
    image: nginx:1.28
    container_name: web-sub1
    volumes:
      - ./s1:/usr/share/nginx/html:ro
  backend:
    image: uv:1
    container_name: backend
    volumes:
      - ./backend:/workspace
    command: ["uv", "run", "fastapi", "run", "--proxy-headers", "--forwarded-allow-ips", "'*'"]